[package]
name = "warp-multiple-api-docs"
description = "Simple warp example api with multiple api docs"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = [
  "Elli Example <example@example.com>"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
env_logger = "0.9.0"
log = "0.4"
futures = "0.3"
utoipa = { path = "../.." }
utoipa-swagger-ui = { path = "../../utoipa-swagger-ui" }

[workspace]
