[package]
name = "utoipa-swagger-ui"
description = "Swagger UI for utoipa"
version = "1.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["swagger-ui", "openapi", "documentation"]
repository = "https://github.com/juhaku/utoipa"
categories = ["web-programming"]
authors = [
  "Juha Kukkonen <juha7kukkonen@gmail.com>"
]

[features]
debug = []

[dependencies]
rust-embed = { version = "6.3", features = ["interpolate-folder-path"] }
mime_guess = { version = "2.0" }
actix-web =  { version = "4", optional = true }
rocket = { version = "0.5.0-rc.1", features = ["json"], optional = true }
utoipa = { version = "1", path = "..", default-features = false, features = [] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }

[package.metadata.docs.rs]
features = ["actix-web", "rocket"]

[build-dependencies]
zip = "0.6"
regex = "1.5"  
lazy_static = "1.4"
